(ns finance-aggregator.plaid.client-test
  "Integration tests for Plaid API client functions.

   These tests require real Plaid sandbox credentials to run.
   Credentials are loaded from the test environment secrets file:
   env/test/resources/secrets.edn.age

   To run these tests:
   1. Generate test key:    bb secrets keygen test
   2. Create test secrets:  bb secrets new test
   3. Run tests:            clojure -M:test --focus finance-aggregator.plaid.client-test"
  (:require
   [clojure.test :refer [deftest is testing use-fixtures]]
   [finance-aggregator.plaid.client :as plaid]
   [finance-aggregator.lib.secrets :as secrets]
   [finance-aggregator.sys :as sys]))

(def ^:dynamic *plaid-config* nil)

(defn- load-plaid-config
  "Load Plaid config from test environment secrets.
   Returns nil if no credentials are available."
  []
  (try
    (let [config (sys/load-configs sys/default-config-files)
          key-file (get config :finance-aggregator.system/secrets-key-file)
          secrets-file (get config :finance-aggregator.system/secrets-file)
          secrets-data (secrets/load-secrets key-file secrets-file)]
      (when-let [plaid (secrets/get-secret secrets-data :plaid)]
        plaid))
    (catch Exception _
      nil)))

(defn plaid-credentials-fixture
  "Fixture that skips tests if Plaid credentials are not available."
  [f]
  (if-let [config (load-plaid-config)]
    (binding [*plaid-config* config]
      (f))
    (println "SKIPPING Plaid client tests - no credentials available. Run: bb secrets new test")))

(use-fixtures :once plaid-credentials-fixture)

(deftest ^:integration create-link-token-test
  (testing "create-link-token generates a link token for Plaid Link initialization"
    (when *plaid-config*
      (let [user-id "test-user-123"
            result (plaid/create-link-token *plaid-config* user-id)]
        (is (string? result) "Should return a link token string")
        (is (not (empty? result)) "Link token should not be empty")
        (is (clojure.string/starts-with? result "link-") "Link token should start with 'link-'")))))

(deftest ^:integration exchange-public-token-test
  (testing "exchange-public-token requires a valid public token from Plaid Link"
    ;; Note: This test cannot be run in isolation because public_tokens
    ;; are only generated by the Plaid Link UI flow. This test documents
    ;; the expected behavior for manual testing.
    (when *plaid-config*
      (is true "exchange-public-token requires a real public_token from Plaid Link UI"))))

(deftest ^:integration fetch-accounts-test
  (testing "fetch-accounts requires a valid access token"
    ;; Note: This test cannot be run in isolation because access_tokens
    ;; are only obtained by exchanging a public_token. This test documents
    ;; the expected behavior for manual testing.
    (when *plaid-config*
      (is true "fetch-accounts requires a real access_token from token exchange"))))

(deftest ^:integration fetch-transactions-test
  (testing "fetch-transactions requires a valid access token"
    ;; Note: This test cannot be run in isolation because access_tokens
    ;; are only obtained by exchanging a public_token. This test documents
    ;; the expected behavior for manual testing.
    (when *plaid-config*
      (is true "fetch-transactions requires a real access_token from token exchange"))))
