(ns user
  "Initial namespace loaded on REPL startup.
   Provides a friendly entry point to the dev environment.")

(defn help []
  (println)
  (println "═════════════════════════════════════════════════════════════")
  (println "  Welcome to Finance Aggregator Backend Development REPL")
  (println "═════════════════════════════════════════════════════════════")
  (println)
  (println "Quick Start:")
  (println "  (dev)                    ;; Load dev tools and switch to dev namespace")
  (println)
  (println "After running (dev), you'll have access to:")
  (println)
  (println "System Management:")
  (println "  (go) or (start)          ;; Start the system")
  (println "  (halt) or (stop)         ;; Stop the system")
  (println "  (reset)                  ;; Reload code and restart system")
  (println "  (reset-all)              ;; Full reset including config")
  (println)
  (println "Component Access:")
  (println "  (system)                 ;; Get full running system")
  (println "  (db)                     ;; Get database component")
  (println "  (server)                 ;; Get HTTP server component")
  (println "  (conn)                   ;; Get database connection")
  (println)
  (println "Database Helpers:")
  (println "  (query '[...])           ;; Execute Datalog query")
  (println "  (all-entities :attr)     ;; Get all entities with attribute")
  (println "  (pull-entity eid)        ;; Pull entity by eid or lookup ref")
  (println "  (transact! [...])        ;; Execute transaction")
  (println)
  (println "Status & Info:")
  (println "  (status)                 ;; Show all components and their status")
  (println "  (db-info)                ;; Database path, entity count, schema info")
  (println "  (server-info)            ;; HTTP server port and health endpoint")
  (println "  (show-schema)            ;; List all schema attributes")
  (println "  (show-config)            ;; Display current system configuration")
  (println)
  (println "Development Utilities:")
  (println "  (refresh)                ;; Reload changed namespaces")
  (println "  (refresh-all)            ;; Reload all namespaces")
  (println "  (clear-db!)              ;; Clear all data from database")
  (println "  (test)                   ;; Run all tests")
  (println "  (test 'namespace)        ;; Run tests for specific namespace")
  (println)
  (println "Test Data Creation:")
  (println "  (create-test-user!)      ;; Create a test user")
  (println "  (create-test-institution!) ;; Create a test institution")
  (println)
  (println "Debug & Introspection:")
  (println "  sc.api/spy               ;; Capture values (via scope-capture)")
  (println "  (source fn-name)         ;; View function source")
  (println "  (doc fn-name)            ;; View function documentation")
  (println "  (dir dev)                ;; List all functions in dev namespace")
  (println)
  (println "Useful Namespaces:")
  (println "  datalevin.core           ;; As 'd' - database operations")
  (println "  clojure.repl             ;; As 'repl' - REPL utilities")
  (println "  clojure.pprint           ;; As 'pp' - pretty printing")
  (println)
  (println "Server Info:")
  (println "  Health:    http://localhost:8080/health")
  (println "  Database:  ./data/dev.db")
  (println)
  (println "Documentation:")
  (println "  doc/implementation/adr-003-backend/repl-quick-reference.md")
  (println "  doc/implementation/adr-003-backend/phase1-implementation-complete-2025-11-25.md")
  (println)
  (println "═════════════════════════════════════════════════════════════")
  (println)
  (println "Ready! Type (dev) to begin. Type (help) to see this again.")
  (println))

(defn dev
  "Load and switch to the 'dev' namespace.
   This loads all development tools and helpers."
  []
  (require 'dev)
  (help)
  (in-ns 'dev)
  :loaded)

;; Show welcome message on REPL startup
(help)
